### ISSUE TITLE
could not find HOI_Detection.pkl and Object_Detection.pkl

### ISSUE THREAD

**Issue by autogyro** [vt-vl-lab/iCAN#1]
Hi Chen:
While I test on my own images as you said, I could not find the pkl files, both HOI_Detection.pkl and Object_Detection.pkl , where can I get its? 
many thanks.
Edward 
--------------------
  File "E:/case/iCAN-master/tools/r-demo.py", line 27, in <module>
    Detection = pickle.load( open( cfg.ROOT_DIR + "/demo/HOI_Detection.pkl", "rb" ) )
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\case\\iCAN-master/demo/HOI_Detection.pkl'

**Comment by gaochen315** [comment]
Hi Edward,

Did you do step 3 and step 4? 
If so, both Object_Detection.pkl and HOI_Detection.pkl will be saved in the demo folder.

**Comment by autogyro** [comment]
Hi Chen
Thanks for your reply, the step 3 and 4 , is  it the  training step? or evaluate step?
Cheers
Ed

**Comment by gaochen315** [comment]
Hi Edward,

In order to test on your own images, you have to follow all steps in the Demo/Test on your own images section. Those are:

1. Clone and setup the tf-faster-rcnn repository.
2. Put your own images in demo/ folder.
3. Detect all objects
4. Detect all HOIs

Step 3 will save Object_Detection.pkl in the demo folder, step 4 will save HOI_Detection.pkl in the demo folder. Then you can use tools/Demo.ipynb to visualize all the HOI detections.

Hope this helps.
