### ISSUE TITLE
About V-COCO training number

### ISSUE THREAD

**Issue by csyanbin** [vt-vl-lab/iCAN#14]
Thanks for the awesome work.
I am trying to run and reproduce the results.

I find a problem: in Trainval_GT_VCOCO.pkl, there are 4971 distinct image ids with 8542 training instances.
While in vcoco_trainval.ids, there are actually 5400 distinct image ids.

My question is why image ids in Trainval_GT_VCOCO.pkl is different with Trainval_GT_VCOCO.pkl?
Is it because some people or objects cannot be detected in V-COCO images using FasterRCNN-FPN?

**Comment by gaochen315** [comment]
In some images, there are no H-O interactions. It could be 1) human are performing actions that don't require objects, e.g., walking, running, etc 2) the object is occluded and labeled as Nan. 

Thus, we won't train our iCAN using these images because there are no annotated H-O pairs.

Hope this helps.

**Comment by csyanbin** [comment]
Thanks so much!
That's quite helpful.

**Comment by Vancause** [comment]
Thanks for your answer and help!
