### ISSUE TITLE
about demo visualization

### ISSUE THREAD

**Issue by baicaiby** [vt-vl-lab/iCAN#6]
Hi, I tested the demo.ipynb, the visualization of your demo image "Djokovic_000X" runs good, while then I put my own picture in the 'demo/' folder, the visualization is not working. There is a line in the code saying "if (ele['image_id'] == image_id):", it seems if picture id is not in ele[], it will not work. Then I changed the "Djokovic_0005.png" into "55.png", there are no more boxes showing in the picture, just as my picture did. After I commenting this line, the boxes always show the same contents as visualizing "Djokovic_000X", no matter how I change the input picture.

Is there anything I did wrong in my steps of visualizing own pictures?

**Comment by gaochen315** [comment]
Hi,

In order to test on your own images, you have to follow all steps in the Demo/Test on your own images section. Those are:

Clone and setup the tf-faster-rcnn repository.
Put your own images in demo/ folder.
Detect all objects
Detect all HOIs
Step 3 will save Object_Detection.pkl in the demo folder, step 4 will save HOI_Detection.pkl in the demo folder. Then you can use tools/Demo.ipynb to visualize all the HOI detections.

Hope this helps.

**Comment by baicaiby** [comment]
Thank you gaochen, my bad, I forgot to detect on my own images, now it works fine.
Thank you for your impressive project!
I thinks this issue can be closed.

**Comment by jbhuang0604** [comment]
Thanks!
